"""The built-in intent table for talksh.

Each entry is (phrase templates, command template, confidence).

Phrase templates are matched case-insensitively against the transcript.
A {slot} in a phrase captures free text (commit message, branch name,
filename, port number, ...) and the same {slot} in the command template
is filled in with what was captured.

This table is the offline brain: with no LLM key configured, these
mappings are all talksh knows, so they cover a developer's daily life.
"""

from __future__ import annotations

# (phrase templates, command template, confidence)
INTENTS: list[tuple[list[str], str, float]] = [
    # ------------------------------------------------------------------ git
    (["git status", "show git status", "what changed"], "git status", 0.98),
    (["git status short", "show git status short", "compact git status"], "git status --short", 0.9),
    (["git add all", "stage all changes", "add all files", "stage everything"], "git add -A", 0.95),
    (["git add {file}", "stage {file}", "add file {file}"], "git add {file}", 0.9),
    (["commit with message {message}", "commit changes with message {message}",
      "make a commit with message {message}"], 'git commit -m "{message}"', 0.9),
    (["commit all with message {message}", "commit everything with message {message}",
      "commit all changes with message {message}"], 'git commit -am "{message}"', 0.9),
    (["amend last commit", "amend commit", "amend the last commit"], "git commit --amend --no-edit", 0.88),
    (["amend commit message {message}", "change last commit message to {message}",
      "update last commit message to {message}"], 'git commit --amend -m "{message}"', 0.88),
    (["git push", "push changes", "push to remote", "push my commits"], "git push", 0.95),
    (["push to {branch}", "git push to {branch}", "push branch {branch}"], "git push origin {branch}", 0.9),
    (["push and set upstream", "push set upstream", "publish branch"], "git push -u origin HEAD", 0.88),
    (["force push", "git force push", "push force"], "git push --force", 0.85),
    (["git pull", "pull changes", "pull from remote", "pull latest"], "git pull", 0.95),
    (["pull from {branch}", "git pull from {branch}"], "git pull origin {branch}", 0.9),
    (["git fetch", "fetch from remote", "fetch updates"], "git fetch", 0.93),
    (["fetch all", "git fetch all", "fetch all remotes"], "git fetch --all", 0.9),
    (["list branches", "show branches", "git branches"], "git branch", 0.93),
    (["list all branches", "show all branches"], "git branch -a", 0.9),
    (["create branch {name}", "new branch {name}", "make branch {name}"], "git branch {name}", 0.9),
    (["switch to branch {name}", "checkout branch {name}", "go to branch {name}",
      "change to branch {name}"], "git checkout {name}", 0.9),
    (["create and switch to branch {name}", "new branch and switch {name}",
      "branch and checkout {name}"], "git checkout -b {name}", 0.9),
    (["switch to main", "go to main branch", "checkout main"], "git checkout main", 0.9),
    (["switch to master", "go to master branch", "checkout master"], "git checkout master", 0.88),
    (["delete branch {name}", "remove branch {name}"], "git branch -d {name}", 0.88),
    (["force delete branch {name}", "delete branch {name} force"], "git branch -D {name}", 0.85),
    (["merge branch {name}", "merge {name} into current", "merge in {name}"], "git merge {name}", 0.88),
    (["merge main", "merge main into current"], "git merge main", 0.88),
    (["rebase onto {branch}", "rebase on {branch}"], "git rebase {branch}", 0.86),
    (["rebase onto main", "rebase on main"], "git rebase main", 0.86),
    (["abort rebase", "cancel rebase"], "git rebase --abort", 0.88),
    (["continue rebase", "resume rebase"], "git rebase --continue", 0.88),
    (["stash changes", "git stash", "stash my changes"], "git stash", 0.93),
    (["stash pop", "apply stash", "pop the stash", "restore stash"], "git stash pop", 0.9),
    (["list stashes", "show stashes", "show stash list"], "git stash list", 0.88),
    (["show stash", "show latest stash"], "git stash show", 0.86),
    (["git log", "show commit history", "show git log"], "git log", 0.93),
    (["git log oneline", "show commit history oneline", "compact git log"], "git log --oneline", 0.9),
    (["show last {n} commits", "git log last {n}", "last {n} commits"], "git log -n {n}", 0.88),
    (["git log for {file}", "show history of {file}", "history of {file}"], "git log --oneline -- {file}", 0.88),
    (["git diff", "show unstaged changes", "show diff"], "git diff", 0.93),
    (["git diff staged", "show staged changes", "diff staged"], "git diff --cached", 0.9),
    (["diff branch {branch}", "compare with branch {branch}", "diff against {branch}"], "git diff {branch}", 0.88),
    (["show commit {commit}", "show details of commit {commit}"], "git show {commit}", 0.88),
    (["show last commit", "show HEAD", "show latest commit"], "git show HEAD", 0.88),
    (["undo last commit keep changes", "soft reset last commit"], "git reset --soft HEAD~1", 0.85),
    (["undo last commit discard changes", "hard reset last commit"], "git reset --hard HEAD~1", 0.82),
    (["reset to commit {commit}", "hard reset to {commit}"], "git reset --hard {commit}", 0.82),
    (["list remotes", "show remotes"], "git remote -v", 0.9),
    (["add remote {name} {url}", "add git remote {name} {url}"], "git remote add {name} {url}", 0.88),
    (["list tags", "show tags", "git tags"], "git tag", 0.9),
    (["create tag {name}", "tag {name}", "new tag {name}"], "git tag {name}", 0.88),
    (["cherry pick {commit}", "cherry-pick {commit}"], "git cherry-pick {commit}", 0.86),
    (["blame {file}", "who changed {file}", "git blame {file}"], "git blame {file}", 0.88),
    (["clean untracked files", "git clean", "remove untracked files"], "git clean -fd", 0.82),
    (["show reflog", "git reflog"], "git reflog", 0.88),
    (["git clone {url}", "clone repo {url}", "clone {url}"], "git clone {url}", 0.9),
    (["git init", "initialize git repo", "init git"], "git init", 0.9),
    (["unstage {file}", "unadd {file}", "remove {file} from staging"], "git restore --staged {file}", 0.88),
    (["discard changes in {file}", "restore {file}", "revert {file}"], "git restore {file}", 0.86),
    (["git move {src} to {dst}"], "git mv {src} {dst}", 0.88),
    (["current branch", "what branch am i on", "show current branch"], "git branch --show-current", 0.9),
    (["show git user", "git config user", "who is the git user"], "git config user.name && git config user.email", 0.85),
    (["git shortlog", "short log", "commit counts by author"], "git shortlog -sn", 0.85),
    # ---------------------------------------------------------------- docker
    (["docker ps", "list running containers", "show running containers"], "docker ps", 0.95),
    (["docker ps all", "list all containers", "show all containers"], "docker ps -a", 0.93),
    (["docker images", "list docker images", "show docker images"], "docker images", 0.93),
    (["compose up", "docker compose up", "start compose", "compose start"], "docker compose up -d", 0.95),
    (["compose down", "docker compose down", "stop compose"], "docker compose down", 0.93),
    (["compose logs", "show compose logs", "docker compose logs"], "docker compose logs", 0.9),
    (["compose logs {service}"], "docker compose logs {service}", 0.9),
    (["follow compose logs", "tail compose logs"], "docker compose logs -f", 0.9),
    (["follow logs for {service}", "tail logs for {service}"], "docker compose logs -f {service}", 0.9),
    (["compose build", "build compose services"], "docker compose build", 0.88),
    (["compose pull", "pull compose images"], "docker compose pull", 0.88),
    (["restart {service}", "restart service {service}", "compose restart {service}"], "docker compose restart {service}", 0.88),
    (["compose restart all", "restart all services"], "docker compose restart", 0.88),
    (["exec into {container}", "shell into {container}", "open shell in {container}"], "docker exec -it {container} sh", 0.88),
    (["bash into {container}", "bash in {container}"], "docker exec -it {container} bash", 0.88),
    (["run container {image}", "docker run {image}"], "docker run -it --rm {image}", 0.88),
    (["stop container {name}", "stop {name} container", "docker stop {name}"], "docker stop {name}", 0.9),
    (["stop all containers", "stop every container"], "docker stop $(docker ps -q)", 0.82),
    (["remove container {name}", "delete container {name}"], "docker rm {name}", 0.86),
    (["remove image {image}", "delete image {image}", "docker rmi {image}"], "docker rmi {image}", 0.86),
    (["docker prune", "prune docker", "clean docker"], "docker system prune -f", 0.8),
    (["list volumes", "docker volumes", "show volumes"], "docker volume ls", 0.88),
    (["list networks", "docker networks", "show networks"], "docker network ls", 0.88),
    (["inspect {container}", "docker inspect {container}"], "docker inspect {container}", 0.86),
    (["docker stats", "container stats"], "docker stats --no-stream", 0.86),
    (["build image {tag}", "docker build {tag}", "build docker image {tag}"], "docker build -t {tag} .", 0.86),
    (["tag image {image} as {tag}", "docker tag {image} {tag}"], "docker tag {image} {tag}", 0.85),
    # ------------------------------------------------------- python / pytest
    (["run tests quietly", "run tests quiet", "quiet tests"], "pytest -q", 0.9),
    (["run tests verbose", "verbose tests"], "pytest -v", 0.9),
    (["run the {target} tests", "run {target} tests", "test the {target} module"], "pytest tests/test_{target}.py -v", 0.9),
    (["run test file {file}", "run tests in {file}", "pytest {file}"], "pytest {file} -v", 0.9),
    (["run last failed tests", "rerun failed tests", "run failed tests"], "pytest --lf", 0.88),
    (["run tests with coverage", "coverage report", "pytest coverage"], "pytest --cov", 0.86),
    (["install {package}", "pip install {package}"], "pip install {package}", 0.93),
    (["install requirements", "pip install requirements"], "pip install -r requirements.txt", 0.93),
    (["install dev requirements"], "pip install -r requirements-dev.txt", 0.88),
    (["install package editable", "pip install editable", "install this package"], "pip install -e .", 0.9),
    (["uninstall {package}", "pip uninstall {package}", "remove package {package}"], "pip uninstall -y {package}", 0.86),
    (["freeze requirements", "pip freeze"], "pip freeze", 0.88),
    (["list installed packages", "pip list", "show installed packages"], "pip list", 0.9),
    (["show package {package}", "pip show {package}"], "pip show {package}", 0.88),
    (["upgrade pip", "update pip"], "pip install --upgrade pip", 0.88),
    (["create virtualenv", "create venv", "make virtualenv", "new venv"], "python -m venv .venv", 0.9),
    (["python version", "show python version"], "python --version", 0.9),
    (["run script {script}", "execute script {script}", "run python script {script}"], "python {script}", 0.88),
    (["run module {module}", "python module {module}"], "python -m {module}", 0.88),
    (["format with black", "run black", "black format"], "black .", 0.86),
    (["format file {file} with black", "black {file}"], "black {file}", 0.86),
    (["lint with ruff", "run ruff", "ruff check"], "ruff check .", 0.86),
    (["typecheck with mypy", "run mypy", "mypy check"], "mypy .", 0.85),
    (["start jupyter", "launch jupyter lab", "open jupyter"], "jupyter lab", 0.85),
    (["pip check", "check pip"], "pip check", 0.86),
    (["upgrade package {package}", "pip upgrade {package}"], "pip install --upgrade {package}", 0.88),
    # ------------------------------------------------------------------ npm
    (["npm install", "install node modules", "install dependencies"], "npm install", 0.93),
    (["npm run {script}", "run npm script {script}"], "npm run {script}", 0.9),
    (["npm start", "start node app"], "npm start", 0.9),
    (["npm test", "run npm tests"], "npm test", 0.9),
    (["npm build", "build node app", "run npm build"], "npm run build", 0.9),
    (["npm dev", "start dev server", "run npm dev"], "npm run dev", 0.9),
    (["npx {cmd}", "run npx {cmd}"], "npx {cmd}", 0.88),
    (["run node {file}", "execute node {file}", "node {file}"], "node {file}", 0.88),
    (["list npm packages", "npm list"], "npm list --depth=0", 0.86),
    (["npm outdated", "check outdated packages"], "npm outdated", 0.86),
    (["npm update", "update node modules"], "npm update", 0.86),
    (["yarn install", "install with yarn"], "yarn install", 0.88),
    (["pnpm install", "install with pnpm"], "pnpm install", 0.88),
    (["node version", "show node version"], "node --version", 0.9),
    (["npm version", "show npm version"], "npm --version", 0.88),
    # ----------------------------------------------------------------- files
    (["list files short", "ls", "short listing"], "ls", 0.9),
    (["list one per line"], "ls -1", 0.85),
    (["show working directory", "print working directory", "where am i"], "pwd", 0.93),
    (["make directory {dir}", "create directory {dir}", "mkdir {dir}"], "mkdir {dir}", 0.9),
    (["make directory parents {dir}", "mkdir parents {dir}", "mkdir recursive {dir}"], "mkdir -p {dir}", 0.88),
    (["create file {file}", "touch {file}", "new file {file}"], "touch {file}", 0.9),
    (["copy {src} to {dst}", "cp {src} to {dst}"], "cp {src} {dst}", 0.9),
    (["copy directory {src} to {dst}", "copy folder {src} to {dst}"], "cp -r {src} {dst}", 0.88),
    (["move {src} to {dst}", "rename {src} to {dst}", "mv {src} to {dst}"], "mv {src} {dst}", 0.9),
    (["delete file {file}", "remove file {file}", "rm {file}"], "rm {file}", 0.88),
    (["remove directory {dir}", "delete directory {dir}", "rmdir {dir}"], "rmdir {dir}", 0.86),
    (["find file {name}", "search for file {name}"], 'find . -name "{name}"', 0.9),
    (["find {name} in {dir}", "look for {name} in {dir}"], 'find {dir} -name "{name}"', 0.88),
    (["grep {pattern}", "search for {pattern}", "search code for {pattern}"], 'grep -rn "{pattern}" .', 0.9),
    (["grep {pattern} in {file}", "search {file} for {pattern}"], 'grep -n "{pattern}" {file}', 0.88),
    (["ripgrep {pattern}", "rg {pattern}", "fast search {pattern}"], 'rg "{pattern}"', 0.88),
    (["show tree", "directory tree", "tree"], "tree -L 2", 0.86),
    (["show tree for {dir}", "tree of {dir}"], "tree -L 2 {dir}", 0.86),
    (["show file {file}", "cat {file}", "print file {file}"], "cat {file}", 0.9),
    (["head of {file}", "first lines of {file}", "show head of {file}"], "head -n 20 {file}", 0.88),
    (["tail of {file}", "last lines of {file}", "show tail of {file}"], "tail -n 20 {file}", 0.88),
    (["follow {file}", "tail follow {file}", "watch {file}"], "tail -f {file}", 0.86),
    (["count lines in {file}", "word count {file}", "wc {file}"], "wc -l {file}", 0.86),
    (["make executable {file}", "chmod plus x {file}"], "chmod +x {file}", 0.88),
    (["chmod {mode} {file}", "set permissions {mode} on {file}"], "chmod {mode} {file}", 0.88),
    (["extract tar {file}", "untar {file}"], "tar -xzf {file}", 0.86),
    (["unzip {file}", "extract zip {file}"], "unzip {file}", 0.86),
    (["create tar {name} from {dir}", "tar {dir} into {name}"], "tar -czf {name} {dir}", 0.86),
    (["zip {dir} into {name}", "create zip {name} from {dir}"], "zip -r {name} {dir}", 0.86),
    (["disk usage of {dir}", "du {dir}", "how big is {dir}"], "du -sh {dir}", 0.88),
    (["which {cmd}", "where is {cmd}", "locate command {cmd}"], "which {cmd}", 0.9),
    (["compare {a} and {b}", "diff files {a} {b}"], "diff {a} {b}", 0.86),
    (["file type of {file}"], "file {file}", 0.85),
    # ---------------------------------------------------------------- network
    (["ping {host}", "ping host {host}"], "ping -c 4 {host}", 0.9),
    (["curl {url}", "fetch url {url}"], "curl -s {url}", 0.9),
    (["curl headers {url}", "show headers for {url}", "head request {url}"], "curl -sI {url}", 0.88),
    (["curl post {url}", "post to {url}"], "curl -s -X POST {url}", 0.86),
    (["download {url}", "wget {url}", "download file {url}"], "wget {url}", 0.88),
    (["ssh {host}", "ssh into {host}", "connect to {host}"], "ssh {host}", 0.9),
    (["ssh {user} at {host}", "ssh as {user} to {host}"], "ssh {user}@{host}", 0.88),
    (["scp {file} to {host}", "secure copy {file} to {host}"], "scp {file} {host}:~/", 0.86),
    (["show ip address", "my ip", "ip address"], "ip addr show", 0.88),
    (["public ip", "what is my public ip"], "curl -s ifconfig.me", 0.86),
    (["traceroute {host}", "trace route to {host}"], "traceroute {host}", 0.85),
    (["dns lookup {host}", "nslookup {host}", "resolve {host}"], "nslookup {host}", 0.86),
    (["dig {host}"], "dig {host} +short", 0.86),
    (["check port {port} on {host}", "test connection to {host} port {port}"], "nc -zv {host} {port}", 0.85),
    (["network connections", "show connections"], "ss -tunap", 0.85),
    # ---------------------------------------------------------------- system
    (["disk free", "show disk space", "how much disk left", "df"], "df -h", 0.9),
    (["memory usage", "show memory", "how much ram", "free memory"], "free -h", 0.9),
    (["cpu info", "show cpu"], "lscpu", 0.85),
    (["show processes", "list processes", "top processes"], "ps aux", 0.88),
    (["find process {name}", "process {name}", "pgrep {name}"], "pgrep -af {name}", 0.88),
    (["kill process {pid}", "kill {pid}"], "kill {pid}", 0.86),
    (["kill by name {name}", "killall {name}", "kill process named {name}"], "killall {name}", 0.84),
    (["force kill {pid}", "kill 9 {pid}"], "kill -9 {pid}", 0.82),
    (["listening ports", "show open ports", "what ports are open"], "ss -tlnp", 0.88),
    (["process on port {port}", "what is on port {port}", "who uses port {port}"], "lsof -i :{port}", 0.88),
    (["system uptime", "uptime", "how long up"], "uptime", 0.9),
    (["hostname", "show hostname"], "hostname", 0.9),
    (["who am i", "current user", "show user"], "whoami", 0.9),
    (["current date", "show date", "what time is it"], "date", 0.9),
    (["show calendar", "cal"], "cal", 0.85),
    (["command history", "show history"], "history", 0.85),
    (["clear screen", "clear terminal", "clear"], "clear", 0.9),
    (["show environment", "print env", "environment variables"], "env", 0.85),
    (["show path", "print path", "echo path"], "echo $PATH", 0.88),
    (["sleep {n} seconds", "wait {n} seconds"], "sleep {n}", 0.85),
    (["cpu count", "how many cpus", "nproc"], "nproc", 0.86),
    (["system info", "uname"], "uname -a", 0.86),
    (["logged in users", "who is logged in"], "who", 0.85),
    (["last logins", "show last logins"], "last -n 10", 0.85),
    (["show mounts", "mounted drives"], "mount | column -t", 0.85),
    (["export {name} {value}", "set env {name} {value}"], "export {name}={value}", 0.85),
    (["print {text}", "echo {text}"], 'echo "{text}"', 0.86),
    # -------------------------------------------------------------- kubernetes
    (["list pods", "show pods", "kubectl get pods", "get pods"], "kubectl get pods", 0.93),
    (["list pods in {namespace}", "pods in namespace {namespace}"], "kubectl get pods -n {namespace}", 0.9),
    (["list services", "show services", "get services"], "kubectl get services", 0.9),
    (["list deployments", "show deployments", "get deployments"], "kubectl get deployments", 0.9),
    (["list nodes", "show nodes", "get nodes"], "kubectl get nodes", 0.9),
    (["describe pod {name}", "pod details {name}"], "kubectl describe pod {name}", 0.88),
    (["pod logs {name}", "logs for pod {name}", "show logs {name}"], "kubectl logs {name}", 0.88),
    (["follow pod logs {name}", "tail pod logs {name}"], "kubectl logs -f {name}", 0.88),
    (["exec into pod {name}", "shell in pod {name}"], "kubectl exec -it {name} -- sh", 0.86),
    (["apply {file}", "kubectl apply {file}"], "kubectl apply -f {file}", 0.88),
    (["delete pod {name}", "remove pod {name}"], "kubectl delete pod {name}", 0.85),
    (["delete resource {file}", "kubectl delete {file}"], "kubectl delete -f {file}", 0.85),
    (["port forward {name} {port}", "forward port {port} to {name}"], "kubectl port-forward {name} {port}:{port}", 0.85),
    (["list namespaces", "show namespaces"], "kubectl get namespaces", 0.88),
    (["use context {name}", "switch context {name}", "kubectl context {name}"], "kubectl config use-context {name}", 0.86),
    (["list contexts", "show contexts"], "kubectl config get-contexts", 0.86),
    (["top pods", "pod resource usage"], "kubectl top pods", 0.85),
    (["restart deployment {name}", "rollout restart {name}"], "kubectl rollout restart deployment/{name}", 0.85),
    (["cluster info"], "kubectl cluster-info", 0.85),
    (["get ingress", "list ingress"], "kubectl get ingress", 0.85),
    # --------------------------------------------------------------- github gh
    (["view repo", "gh repo view", "show repo"], "gh repo view", 0.88),
    (["list pull requests", "show prs", "gh pr list"], "gh pr list", 0.9),
    (["create pull request", "open pr", "gh pr create"], "gh pr create", 0.88),
    (["pr status", "show my prs", "gh pr status"], "gh pr status", 0.88),
    (["checkout pr {n}", "gh checkout pr {n}"], "gh pr checkout {n}", 0.86),
    (["merge pr {n}", "gh merge pr {n}"], "gh pr merge {n}", 0.85),
    (["list issues", "show issues", "gh issue list"], "gh issue list", 0.9),
    (["create issue", "open issue", "gh issue create"], "gh issue create", 0.88),
    (["view issue {n}", "show issue {n}"], "gh issue view {n}", 0.86),
    (["list releases", "show releases"], "gh release list", 0.88),
    (["create release {tag}", "new release {tag}"], "gh release create {tag}", 0.85),
    (["list workflows", "show workflows"], "gh workflow list", 0.86),
    (["list runs", "show workflow runs"], "gh run list", 0.86),
    (["gh auth status", "check gh login"], "gh auth status", 0.86),
    (["open repo in browser", "gh browse"], "gh browse", 0.85),
]


def mapping_count() -> int:
    """Total number of phrase -> command mappings in the table."""
    return sum(len(phrases) for phrases, _, _ in INTENTS)
